theme: jekyll-theme-minimal
future: false

# Site settings
permalink: pretty

# Pages permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext

site:
  title: "$2117.91"
  description: "Let's see how fast I can make $2117.91 USD. The goal is by end of day, Sunday March 18th."